Fixes TypeError issue in Ember 1.10
After upgrading to Ember 1.10 the Application complains about "Uncaught TypeError: undefined is not a function". For some unknown reason Ember.assert also seems to execute the Pusher function. To overcome this I am explicitly checking if Pusher is undefined.